
#日志文件位置
LogFile=/var/log/zabbix/zabbix_server.log 
#日志文件大小，0表示不轮询更新
LogFileSize=0



#pid文件位置
PidFile=/var/run/zabbix/zabbix_server.pid

#socker文件位置
SocketDir=/var/run/zabbix

#数据库地址
DBHost=
#数据库名
DBName=zabbix
#数据库用户名
DBUser=zabbix
#数据库密码
DBPassword=zabbix
#数据库端口
DBPort=

