
[global]
#监控pool有没有冗余，如果pool只有1个副本则会警告
mon_warn_on_pool_no_redundancy = false

#pool的副本数，默认3，如果集群只有一个节点的时候，可以设置为1
osd_pool_default_size = 1
#最小pool的副本数，如果pool的副本数小于此值，则不提供I/O服务，默认为0
osd_pool_default_min_size = 0


#可以删除pool
mon_allow_pool_delete = true
