

# 日志级别 (INFO, WARNING, ERROR, FATAL)
sys_log_level = INFO

# ports for admin, web, heartbeat service 
be_port = 9060
#web端口，可通过浏览器查看
webserver_port = 8040
#心跳端口
heartbeat_service_port = 9050

brpc_port = 8060

# 多个网卡时必须指定某个，或者几个网段，默认为空，随机选择一个网段
# priority_networks = 10.10.10.0/24;192.168.0.0/16

# data root path, separate by ';'
# you can specify the storage medium of each root path, HDD or SSD, seperate by ','
# eg:
# storage_root_path = /data1,medium:HDD;/data2,medium:SSD;/data3
# /data1, HDD;
# /data2, SSD;
# /data3, HDD(default);
#
# Default value is ${STARROCKS_HOME}/storage, you should create it by hand.
# storage_root_path = ${STARROCKS_HOME}/storage

# Advanced configurations
# sys_log_dir = ${STARROCKS_HOME}/log
# sys_log_roll_mode = SIZE-MB-1024
# sys_log_roll_num = 10
# sys_log_verbose_modules = *
# log_buffer_level = -1

default_rowset_type = beta
