#日志目录，${STARROCKS_HOME}代表fe目录 。${STARROCKS_HOME}/log 即 fe/log
LOG_DIR = ${STARROCKS_HOME}/log

#时间
DATE = "$(date +%Y%m%d-%H%M%S)"

#JAVA_HOME jdk路径
JAVA_HOME=/xxx
#jdk8
JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$STARROCKS_HOME/log/fe.gc.log.$DATE"
#jdk9以及以上
JAVA_OPTS_FOR_JDK_9="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xlog:gc*:$STARROCKS_HOME/log/fe.gc.log.$DATE:time"

# 日志级别，(DEBUG, INFO, WARN, ERROR, FATAL)
sys_log_level = INFO

# 元数据目录 不写默认 ${STARROCKS_HOME}/meta
meta_dir = ${STARROCKS_HOME}/meta

#web端口，可通过浏览器查看状态
http_port = 8030
rpc_port = 9020
#fe的jdbc端口，通过mysql客户端去连接的端口，相当于mysql的3306
query_port = 9030
#fe集群之间通信的端口
edit_log_port = 9010
mysql_service_nio_enabled = true

# 多个网卡时必须指定某个，或者几个网段，默认为空，随机选择一个网段
# priority_networks = 10.10.10.0/24;192.168.0.0/16